# Generated by Django 2.1 on 2018-08-18 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdbID',
            field=models.CharField(default='', max_length=1000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='year',
            field=models.IntegerField(default=2000),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'year', 'imdbID')},
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title'], name='core_movie_title_e933de_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['year'], name='core_movie_year_a638fe_idx'),
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['imdbID'], name='core_movie_imdbID_40fa45_idx'),
        ),
    ]
