# Generated by Django 2.1 on 2018-08-18 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180818_1856'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='movie',
            name='core_movie_title_e933de_idx',
        ),
        migrations.RemoveIndex(
            model_name='movie',
            name='core_movie_imdbID_40fa45_idx',
        ),
        migrations.AddIndex(
            model_name='movie',
            index=models.Index(fields=['title', 'year'], name='core_movie_title_986d9f_idx'),
        ),
    ]
