# Generated by Django 2.1 on 2018-08-18 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20180818_2325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='metascore',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
