# Generated by Django 2.1 on 2018-08-18 23:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20180818_2337'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_id',
            new_name='imdbid',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_rating',
            new_name='imdbrating',
        ),
        migrations.RenameField(
            model_name='movie',
            old_name='imdb_votes',
            new_name='imdbvotes',
        ),
        migrations.AlterUniqueTogether(
            name='movie',
            unique_together={('title', 'year', 'imdbid')},
        ),
    ]
