# Generated by Django 2.1 on 2018-08-19 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20180818_2355'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default='1970-01-01 00:00'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movie',
            name='modified_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
