# Generated by Django 2.1 on 2018-08-19 17:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='box_office',
            new_name='boxoffice',
        ),
    ]
