# Generated by Django 2.1 on 2018-08-19 18:08

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20180819_1745'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='ratings',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
            preserve_default=False,
        ),
    ]
